# Default color configuration for Skog UI

# See tcell source code to take and valid color name of provide the RGB in format "#ffffff"
# https://github.com/gdamore/tcell/blob/main/color.go
# Components colors have more priority that root 'background' and 'foreground'
# Put 'default' to apply color of your terminal
skog:
  profile:
    fgColor: "white"
    bgColor: "default"
  status:
    fgColor: "grey"
    bgColor: "default"
  label:
    fgColor: "orange"
    bgColor: "default"
  keybinding:
    key: "grey"
    value: "grey"
  search:
    fgColor: "white"
    bgColor: "default"
  selection:
    fgColor: "black"
    bgColor: "white"
  placeholder: "grey"
  title: "white"
  border: "white"
  background: "default"
  foreground: "white"
